name: Ping AI Recipe Sites

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch: # Optional: allows manual triggering

jobs:
  ping-sites:
    runs-on: ubuntu-latest

    steps:
      - name: Call Tommie's Grocery Price Checker
        run: curl -s https://grocery-price-checker.onrender.com/

      # - name: Call ai-recipe-generator-search
      #   run: curl -s https://grocery-price-checker.onrender.com/admin/category/api
